behaviors:
  MoveToGoal:
    trainer_type: sac
    hyperparameters:
      batch_size: 1024
      buffer_size: 100000
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 5
      save_replay_buffer: false
      init_entcoef: 0.75
      
    network_settings:
      hidden_units: 128
      num_layers: 2  
      activation: relu  
    reward_signals:
      extrinsic:
        strength: 1.0  
        gamma: 0.99  
    keep_checkpoints: 5  
    checkpoint_interval: 50000  
    max_steps: 2000000  
    time_horizon: 64  
    summary_freq: 1000  
    threaded: true 
