behaviors:
  MoveToGoal:
    trainer_type: sac
    hyperparameters:
      batch_size: 395
      buffer_size: 624729
      learning_rate: 0.00046759946516392183
      learning_rate_schedule: constant
      buffer_init_steps: 10000
      tau: 0.005
      steps_per_update: 5
      save_replay_buffer: false
      init_entcoef: 0.14832095005450271
      
    network_settings:
      hidden_units: 123
      num_layers: 2  
      activation: relu  
    reward_signals:
      extrinsic:
        strength: 1.0  
        gamma: 0.9847902438665549  
    keep_checkpoints: 5  
    checkpoint_interval: 50000  
    max_steps: 2000000  
    time_horizon: 64  
    summary_freq: 1000  
    threaded: true 
