behaviors:
  MoveToGoal:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 30720
      learning_rate: 3.4131624696535314e-05
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 40
      learning_rate_schedule: linear 
    network_settings:
      normalize: false
      hidden_units: 384
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.9657565304412798
        strength: 1.0
    max_steps: 500000
    time_horizon: 64
    summary_freq: 1000